services:
    _defaults:
        autowire: false
        autoconfigure: false
        public: true

    Claroline\AuthenticationBundle\Serializer\OauthUserSerializer:
        tags: [claroline.serializer]
        arguments:
            - '@Claroline\AppBundle\Persistence\ObjectManager'
            - '@Claroline\CoreBundle\API\Serializer\User\UserSerializer'
