services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository:
            autowire: false
            tags: [doctrine.repository_service]

    Claroline\CoreBundle\Repository\Tool\AdministrationToolRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\Tool\OrderedToolRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\ResourceActionRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\ResourceTypeRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\Tool\ToolRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@claroline.manager.plugin_manager'

    Claroline\CoreBundle\Repository\UserRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@Claroline\CoreBundle\Library\Configuration\PlatformConfigurationHandler'

    Claroline\CoreBundle\Repository\Log\LogRepository:
        arguments:
          - '@Symfony\Bridge\Doctrine\RegistryInterface'
          - '@Claroline\CoreBundle\API\Finder\Log\LogFinder'
